var searchData=
[
  ['o_20setting_20in_20standby_20shutdown_20mode_0',['GPIO bit number for I/O setting in standby/shutdown mode',['../group___p_w_r_ex___g_p_i_o___bit___number.html',1,'']]],
  ['of_20stop_20bits_1',['UART Number of Stop Bits',['../group___u_a_r_t___stop___bits.html',1,'']]],
  ['of_20view_2',['I2C Transfer Direction Master Point of View',['../group___i2_c___x_f_e_r_d_i_r_e_c_t_i_o_n.html',1,'']]],
  ['offset_3',['SAI Block FS Offset',['../group___s_a_i___block___f_s___offset.html',1,'']]],
  ['offstate_20selection_20for_20idle_20mode_20state_4',['TIM OSSI OffState Selection for Idle mode state',['../group___t_i_m___o_s_s_i___off___state___selection__for___idle__mode__state.html',1,'']]],
  ['offstate_20selection_20for_20run_20mode_20state_5',['TIM OSSR OffState Selection for Run mode state',['../group___t_i_m___o_s_s_r___off___state___selection__for___run__mode__state.html',1,'']]],
  ['on_20gpio_6',['Fast-mode Plus on GPIO',['../group___s_y_s_c_f_g___fast_mode_plus___g_p_i_o.html',1,'']]],
  ['on_20rdp_20level_20type_7',['FLASH Option Bytes PCROP On RDP Level Type',['../group___f_l_a_s_h___o_b___p_c_r_o_p___r_d_p.html',1,'']]],
  ['on_20reset_20type_8',['FLASH Option Bytes User SRAM2 Erase On Reset Type',['../group___f_l_a_s_h___o_b___u_s_e_r___s_r_a_m2___r_s_t.html',1,'']]],
  ['on_20rx_20error_9',['UART Advanced Feature DMA Disable On Rx Error',['../group___u_a_r_t___d_m_a___disable__on___rx___error.html',1,'']]],
  ['on_20shutdown_10',['FLASH Option Bytes User Reset On Shutdown',['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_h_u_t_d_o_w_n.html',1,'']]],
  ['on_20standby_11',['On Standby',['../group___f_l_a_s_h___o_b___u_s_e_r___i_w_d_g___s_t_a_n_d_b_y.html',1,'FLASH Option Bytes User IWDG Mode On Standby'],['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_t_a_n_d_b_y.html',1,'FLASH Option Bytes User Reset On Standby']]],
  ['on_20stop_12',['On Stop',['../group___f_l_a_s_h___o_b___u_s_e_r___i_w_d_g___s_t_o_p.html',1,'FLASH Option Bytes User IWDG Mode On Stop'],['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_t_o_p.html',1,'FLASH Option Bytes User Reset On Stop']]],
  ['one_20bit_20sampling_20method_13',['UART One Bit Sampling Method',['../group___u_a_r_t___one_bit___sampling.html',1,'']]],
  ['one_20pulse_20functions_14',['One Pulse functions',['../group___t_i_m_ex___exported___functions___group4.html',1,'Extended Timer Complementary One Pulse functions'],['../group___t_i_m___exported___functions___group5.html',1,'TIM One Pulse functions']]],
  ['one_20pulse_20mode_15',['TIM One Pulse Mode',['../group___t_i_m___one___pulse___mode.html',1,'']]],
  ['opamp_20aliased_20defines_20maintained_20for_20legacy_20purpose_16',['HAL OPAMP Aliased Defines maintained for legacy purpose',['../group___h_a_l___o_p_a_m_p___aliased___defines.html',1,'']]],
  ['opamp_20aliased_20macros_20maintained_20for_20legacy_20purpose_17',['HAL OPAMP Aliased Macros maintained for legacy purpose',['../group___h_a_l___o_p_a_m_p___aliased___macros.html',1,'']]],
  ['operation_20functions_18',['operation functions',['../group___i2_c___exported___functions___group2.html',1,'Input and Output operation functions'],['../group___e_x_t_i___exported___functions___group2.html',1,'IO operation functions'],['../group___g_p_i_o___exported___functions___group2.html',1,'IO operation functions'],['../group___u_a_r_t___exported___functions___group2.html',1,'IO operation functions']]],
  ['option_20bytes_20pcrop_20on_20rdp_20level_20type_19',['FLASH Option Bytes PCROP On RDP Level Type',['../group___f_l_a_s_h___o_b___p_c_r_o_p___r_d_p.html',1,'']]],
  ['option_20bytes_20read_20protection_20',['FLASH Option Bytes Read Protection',['../group___f_l_a_s_h___o_b___read___protection.html',1,'']]],
  ['option_20bytes_20type_21',['FLASH Option Bytes Type',['../group___f_l_a_s_h___o_b___type.html',1,'']]],
  ['option_20bytes_20user_20boot1_20type_22',['FLASH Option Bytes User BOOT1 Type',['../group___f_l_a_s_h___o_b___u_s_e_r__n_b_o_o_t1.html',1,'']]],
  ['option_20bytes_20user_20bor_20level_23',['FLASH Option Bytes User BOR Level',['../group___f_l_a_s_h___o_b___u_s_e_r___b_o_r___l_e_v_e_l.html',1,'']]],
  ['option_20bytes_20user_20iwdg_20mode_20on_20standby_24',['FLASH Option Bytes User IWDG Mode On Standby',['../group___f_l_a_s_h___o_b___u_s_e_r___i_w_d_g___s_t_a_n_d_b_y.html',1,'']]],
  ['option_20bytes_20user_20iwdg_20mode_20on_20stop_25',['FLASH Option Bytes User IWDG Mode On Stop',['../group___f_l_a_s_h___o_b___u_s_e_r___i_w_d_g___s_t_o_p.html',1,'']]],
  ['option_20bytes_20user_20iwdg_20type_26',['FLASH Option Bytes User IWDG Type',['../group___f_l_a_s_h___o_b___u_s_e_r___i_w_d_g___s_w.html',1,'']]],
  ['option_20bytes_20user_20reset_20on_20shutdown_27',['FLASH Option Bytes User Reset On Shutdown',['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_h_u_t_d_o_w_n.html',1,'']]],
  ['option_20bytes_20user_20reset_20on_20standby_28',['FLASH Option Bytes User Reset On Standby',['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_t_a_n_d_b_y.html',1,'']]],
  ['option_20bytes_20user_20reset_20on_20stop_29',['FLASH Option Bytes User Reset On Stop',['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_t_o_p.html',1,'']]],
  ['option_20bytes_20user_20sram2_20erase_20on_20reset_20type_30',['FLASH Option Bytes User SRAM2 Erase On Reset Type',['../group___f_l_a_s_h___o_b___u_s_e_r___s_r_a_m2___r_s_t.html',1,'']]],
  ['option_20bytes_20user_20sram2_20parity_20check_20type_31',['FLASH Option Bytes User SRAM2 Parity Check Type',['../group___f_l_a_s_h___o_b___u_s_e_r___s_r_a_m2___p_e.html',1,'']]],
  ['option_20bytes_20user_20type_32',['FLASH Option Bytes User Type',['../group___f_l_a_s_h___o_b___u_s_e_r___type.html',1,'']]],
  ['option_20bytes_20user_20wwdg_20type_33',['FLASH Option Bytes User WWDG Type',['../group___f_l_a_s_h___o_b___u_s_e_r___w_w_d_g___s_w.html',1,'']]],
  ['options_34',['I2C Sequential Transfer Options',['../group___i2_c___x_f_e_r_o_p_t_i_o_n_s.html',1,'']]],
  ['or_203_35',['TIM Group Channel 5 and Channel 1, 2 or 3',['../group___t_i_m___group___channel5.html',1,'']]],
  ['or_20disabled_20status_36',['or Disabled Status',['../group___r_c_c___a_h_b1___peripheral___clock___enable___disable___status.html',1,'AHB1 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_h_b1___clock___sleep___enable___disable___status.html',1,'AHB1 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_h_b2___clock___enable___disable___status.html',1,'AHB2 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_h_b2___clock___sleep___enable___disable___status.html',1,'AHB2 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_h_b3___clock___enable___disable___status.html',1,'AHB3 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_h_b3___clock___sleep___enable___disable___status.html',1,'AHB3 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_p_b1___clock___enable___disable___status.html',1,'APB1 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_p_b1___clock___sleep___enable___disable___status.html',1,'APB1 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_p_b2___clock___enable___disable___status.html',1,'APB2 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_p_b2___clock___sleep___enable___disable___status.html',1,'APB2 Peripheral Clock Sleep Enabled or Disabled Status']]],
  ['or_20stop_20mode_37',['I2C Start or Stop Mode',['../group___i2_c___s_t_a_r_t___s_t_o_p___m_o_d_e.html',1,'']]],
  ['oscillator_20type_38',['Oscillator Type',['../group___r_c_c___oscillator___type.html',1,'']]],
  ['ossi_20offstate_20selection_20for_20idle_20mode_20state_39',['TIM OSSI OffState Selection for Idle mode state',['../group___t_i_m___o_s_s_i___off___state___selection__for___idle__mode__state.html',1,'']]],
  ['ossr_20offstate_20selection_20for_20run_20mode_20state_40',['TIM OSSR OffState Selection for Run mode state',['../group___t_i_m___o_s_s_r___off___state___selection__for___run__mode__state.html',1,'']]],
  ['out_20value_41',['UART polling-based communications time-out value',['../group___u_a_r_t___time_out___value.html',1,'']]],
  ['output_42',['PLL Clock Output',['../group___r_c_c___p_l_l___clock___output.html',1,'']]],
  ['output_20compare_20and_20pwm_20modes_43',['TIM Output Compare and PWM Modes',['../group___t_i_m___output___compare__and___p_w_m__modes.html',1,'']]],
  ['output_20compare_20functions_44',['Output Compare functions',['../group___t_i_m_ex___exported___functions___group2.html',1,'Extended Timer Complementary Output Compare functions'],['../group___t_i_m___exported___functions___group2.html',1,'TIM Output Compare functions']]],
  ['output_20compare_20idle_20state_45',['Output Compare Idle State',['../group___t_i_m___output___compare___n___idle___state.html',1,'TIM Complementary Output Compare Idle State'],['../group___t_i_m___output___compare___idle___state.html',1,'TIM Output Compare Idle State']]],
  ['output_20compare_20polarity_46',['Output Compare Polarity',['../group___t_i_m___output___compare___n___polarity.html',1,'TIM Complementary Output Compare Polarity'],['../group___t_i_m___output___compare___polarity.html',1,'TIM Output Compare Polarity']]],
  ['output_20compare_20state_47',['Output Compare State',['../group___t_i_m___output___compare___n___state.html',1,'TIM Complementary Output Compare State'],['../group___t_i_m___output___compare___state.html',1,'TIM Output Compare State']]],
  ['output_20drive_48',['SAI Block Output Drive',['../group___s_a_i___block___output___drive.html',1,'']]],
  ['output_20enable_49',['TIM Automatic Output Enable',['../group___t_i_m___a_o_e___bit___set___reset.html',1,'']]],
  ['output_20fast_20state_50',['TIM Output Fast State',['../group___t_i_m___output___fast___state.html',1,'']]],
  ['output_20operation_20functions_51',['Input and Output operation functions',['../group___i2_c___exported___functions___group2.html',1,'']]],
  ['over_20sampling_52',['UART Over Sampling',['../group___u_a_r_t___over___sampling.html',1,'']]],
  ['overrun_20disable_53',['UART Advanced Feature Overrun Disable',['../group___u_a_r_t___overrun___disable.html',1,'']]],
  ['own_20address2_20masks_54',['I2C Own Address2 Masks',['../group___i2_c___o_w_n___a_d_d_r_e_s_s2___m_a_s_k_s.html',1,'']]]
];
