var searchData=
[
  ['sai_0',['SAI',['../group___s_a_i.html',1,'']]],
  ['sai_20aliased_20macros_20maintained_20for_20legacy_20purpose_1',['HAL SAI Aliased Macros maintained for legacy purpose',['../group___h_a_l___s_a_i___aliased___macros.html',1,'']]],
  ['sai_20audio_20frequency_2',['SAI Audio Frequency',['../group___s_a_i___audio___frequency.html',1,'']]],
  ['sai_20block_20clock_20strobing_3',['SAI Block Clock Strobing',['../group___s_a_i___block___clock___strobing.html',1,'']]],
  ['sai_20block_20companding_20mode_4',['SAI Block Companding Mode',['../group___s_a_i___block___companding___mode.html',1,'']]],
  ['sai_20block_20data_20size_5',['SAI Block Data Size',['../group___s_a_i___block___data___size.html',1,'']]],
  ['sai_20block_20fifo_20status_20level_6',['SAI Block Fifo Status Level',['../group___s_a_i___block___fifo___status___level.html',1,'']]],
  ['sai_20block_20fifo_20threshold_7',['SAI Block Fifo Threshold',['../group___s_a_i___block___fifo___threshold.html',1,'']]],
  ['sai_20block_20flags_20definition_8',['SAI Block Flags Definition',['../group___s_a_i___block___flags___definition.html',1,'']]],
  ['sai_20block_20fs_20definition_9',['SAI Block FS Definition',['../group___s_a_i___block___f_s___definition.html',1,'']]],
  ['sai_20block_20fs_20offset_10',['SAI Block FS Offset',['../group___s_a_i___block___f_s___offset.html',1,'']]],
  ['sai_20block_20fs_20polarity_11',['SAI Block FS Polarity',['../group___s_a_i___block___f_s___polarity.html',1,'']]],
  ['sai_20block_20interrupts_20definition_12',['SAI Block Interrupts Definition',['../group___s_a_i___block___interrupts___definition.html',1,'']]],
  ['sai_20block_20mode_13',['SAI Block Mode',['../group___s_a_i___block___mode.html',1,'']]],
  ['sai_20block_20msb_20lsb_20transmission_14',['SAI Block MSB LSB transmission',['../group___s_a_i___block___m_s_b___l_s_b__transmission.html',1,'']]],
  ['sai_20block_20mute_20value_15',['SAI Block Mute Value',['../group___s_a_i___block___mute___value.html',1,'']]],
  ['sai_20block_20nodivider_16',['SAI Block NoDivider',['../group___s_a_i___block___no_divider.html',1,'']]],
  ['sai_20block_20output_20drive_17',['SAI Block Output Drive',['../group___s_a_i___block___output___drive.html',1,'']]],
  ['sai_20block_20protocol_18',['SAI Block Protocol',['../group___s_a_i___block___protocol.html',1,'']]],
  ['sai_20block_20slot_20active_19',['SAI Block Slot Active',['../group___s_a_i___block___slot___active.html',1,'']]],
  ['sai_20block_20slot_20size_20',['SAI Block Slot Size',['../group___s_a_i___block___slot___size.html',1,'']]],
  ['sai_20block_20synchronization_21',['SAI Block Synchronization',['../group___s_a_i___block___synchronization.html',1,'']]],
  ['sai_20error_20code_22',['SAI Error Code',['../group___s_a_i___error___code.html',1,'']]],
  ['sai_20exported_20constants_23',['SAI Exported Constants',['../group___s_a_i___exported___constants.html',1,'']]],
  ['sai_20exported_20macros_24',['SAI Exported Macros',['../group___s_a_i___exported___macros.html',1,'']]],
  ['sai_20exported_20types_25',['SAI Exported Types',['../group___s_a_i___exported___types.html',1,'']]],
  ['sai_20external_20synchronisation_26',['SAI External synchronisation',['../group___s_a_i___block___sync_ext.html',1,'']]],
  ['sai_20frame_20structure_20definition_27',['SAI Frame Structure definition',['../group___s_a_i___frame___structure__definition.html',1,'']]],
  ['sai_20handle_20structure_20definition_28',['SAI Handle Structure definition',['../group___s_a_i___handle___structure__definition.html',1,'']]],
  ['sai_20init_20structure_20definition_29',['SAI Init Structure definition',['../group___s_a_i___init___structure__definition.html',1,'']]],
  ['sai_20mono_20stereo_20mode_30',['SAI Mono Stereo Mode',['../group___s_a_i___mono___stereo___mode.html',1,'']]],
  ['sai_20private_20functions_31',['SAI Private Functions',['../group___s_a_i___private___functions.html',1,'']]],
  ['sai_20private_20macros_32',['SAI Private Macros',['../group___s_a_i___private___macros.html',1,'']]],
  ['sai_20protocol_20data_20size_33',['SAI protocol data size',['../group___s_a_i___protocol___data_size.html',1,'']]],
  ['sai_20slot_20structure_20definition_34',['SAI Slot Structure definition',['../group___s_a_i___slot___structure__definition.html',1,'']]],
  ['sai_20supported_20protocol_35',['SAI Supported protocol',['../group___s_a_i___protocol.html',1,'']]],
  ['sai_20tristate_20management_36',['SAI TRIState Management',['../group___s_a_i___t_r_i_state___management.html',1,'']]],
  ['sai_5fexported_5ffunctions_37',['SAI_Exported_Functions',['../group___s_a_i___exported___functions.html',1,'']]],
  ['sai_5fexported_5ffunctions_5fgroup1_38',['SAI_Exported_Functions_Group1',['../group___s_a_i___exported___functions___group1.html',1,'']]],
  ['sai_5fexported_5ffunctions_5fgroup2_39',['SAI_Exported_Functions_Group2',['../group___s_a_i___exported___functions___group2.html',1,'']]],
  ['sai_5fexported_5ffunctions_5fgroup3_40',['SAI_Exported_Functions_Group3',['../group___s_a_i___exported___functions___group3.html',1,'']]],
  ['sampling_41',['UART Over Sampling',['../group___u_a_r_t___over___sampling.html',1,'']]],
  ['sampling_20method_42',['UART One Bit Sampling Method',['../group___u_a_r_t___one_bit___sampling.html',1,'']]],
  ['sau_20functions_43',['SAU Functions',['../group___c_m_s_i_s___core___s_a_u_functions.html',1,'']]],
  ['scale_44',['PWR Regulator voltage scale',['../group___p_w_r_ex___regulator___voltage___scale.html',1,'']]],
  ['scb_45',['System Control Block (SCB)',['../group___c_m_s_i_s___s_c_b.html',1,'']]],
  ['scb_20scnscb_46',['System Controls not in SCB (SCnSCB)',['../group___c_m_s_i_s___s_cn_s_c_b.html',1,'']]],
  ['scnscb_47',['System Controls not in SCB (SCnSCB)',['../group___c_m_s_i_s___s_cn_s_c_b.html',1,'']]],
  ['sd_20mmc_20aliased_20macros_20maintained_20for_20legacy_20purpose_48',['HAL SD/MMC Aliased Macros maintained for legacy purpose',['../group___h_a_l___s_d___aliased___macros.html',1,'']]],
  ['select_20management_49',['SPI Slave Select Management',['../group___s_p_i___slave___select__management.html',1,'']]],
  ['selection_50',['Selection',['../group___r_c_c_ex___periph___clock___selection.html',1,'Periph Clock Selection'],['../group___t_i_m___input___capture___selection.html',1,'TIM Input Capture Selection'],['../group___t_i_m___master___mode___selection.html',1,'TIM Master Mode Selection'],['../group___t_i_m___t_i1___selection.html',1,'TIM TI1 Input Selection'],['../group___t_i_m___trigger___selection.html',1,'TIM Trigger Selection'],['../group___u_a_r_t___half___duplex___selection.html',1,'UART Half Duplex Selection'],['../group___u_a_r_t___wake_up__from___stop___selection.html',1,'UART WakeUp From Stop Selection']]],
  ['selection_51',['selection',['../group___t_i_m___c_c___d_m_a___request.html',1,'CCx DMA request selection'],['../group___g_p_i_o_ex___alternate__function__selection.html',1,'GPIOEx Alternate function selection'],['../group___p_w_r_ex___v_b_a_t___battery___charging___selection.html',1,'PWR battery charging resistor selection']]],
  ['selection_202_20trgo2_52',['TIM Master Mode Selection 2 (TRGO2)',['../group___t_i_m___master___mode___selection__2.html',1,'']]],
  ['selection_20for_20idle_20mode_20state_53',['TIM OSSI OffState Selection for Idle mode state',['../group___t_i_m___o_s_s_i___off___state___selection__for___idle__mode__state.html',1,'']]],
  ['selection_20for_20run_20mode_20state_54',['TIM OSSR OffState Selection for Run mode state',['../group___t_i_m___o_s_s_r___off___state___selection__for___run__mode__state.html',1,'']]],
  ['sensor_20functions_55',['Extended Timer Hall Sensor functions',['../group___t_i_m_ex___exported___functions___group1.html',1,'']]],
  ['sequential_20transfer_20options_56',['I2C Sequential Transfer Options',['../group___i2_c___x_f_e_r_o_p_t_i_o_n_s.html',1,'']]],
  ['setting_20in_20standby_20shutdown_20mode_57',['GPIO bit number for I/O setting in standby/shutdown mode',['../group___p_w_r_ex___g_p_i_o___bit___number.html',1,'']]],
  ['shift_20to_20apply_20to_20retrieve_20polarity_20information_20from_20pwr_5fwakeup_5fpiny_5fxxx_20constants_58',['Shift to apply to retrieve polarity information from PWR_WAKEUP_PINy_xxx constants',['../group___p_w_r_ex___w_u_p___polarity.html',1,'']]],
  ['shutdown_59',['FLASH Option Bytes User Reset On Shutdown',['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_h_u_t_d_o_w_n.html',1,'']]],
  ['shutdown_20mode_60',['GPIO bit number for I/O setting in standby/shutdown mode',['../group___p_w_r_ex___g_p_i_o___bit___number.html',1,'']]],
  ['signature_61',['DEVICE ELECTRONIC SIGNATURE',['../group___u_t_i_l_s___e_f___d_e_v_i_c_e___e_l_e_c_t_r_o_n_i_c___s_i_g_n_a_t_u_r_e.html',1,'']]],
  ['simd_20intrinsics_62',['CMSIS SIMD Intrinsics',['../group___c_m_s_i_s___s_i_m_d__intrinsics.html',1,'']]],
  ['size_63',['Size',['../group___i2_c___m_e_m_o_r_y___a_d_d_r_e_s_s___s_i_z_e.html',1,'I2C Memory Address Size'],['../group___s_a_i___block___data___size.html',1,'SAI Block Data Size'],['../group___s_a_i___block___slot___size.html',1,'SAI Block Slot Size'],['../group___s_p_i___data___size.html',1,'SPI Data Size']]],
  ['size_64',['size',['../group___d_m_a___memory__data__size.html',1,'DMA Memory data size'],['../group___d_m_a___peripheral__data__size.html',1,'DMA Peripheral data size'],['../group___s_a_i___protocol___data_size.html',1,'SAI protocol data size']]],
  ['slave_20mode_65',['TIM Master/Slave Mode',['../group___t_i_m___master___slave___mode.html',1,'']]],
  ['slave_20mode_66',['TIM Slave mode',['../group___t_i_m___slave___mode.html',1,'']]],
  ['slave_20select_20management_67',['SPI Slave Select Management',['../group___s_p_i___slave___select__management.html',1,'']]],
  ['sleep_20enable_20disable_68',['Sleep Enable Disable',['../group___r_c_c___a_h_b1___clock___sleep___enable___disable.html',1,'AHB1 Peripheral Clock Sleep Enable Disable'],['../group___r_c_c___a_h_b2___clock___sleep___enable___disable.html',1,'AHB2 Peripheral Clock Sleep Enable Disable'],['../group___r_c_c___a_h_b3___clock___sleep___enable___disable.html',1,'AHB3 Peripheral Clock Sleep Enable Disable'],['../group___r_c_c___a_p_b1___clock___sleep___enable___disable.html',1,'APB1 Peripheral Clock Sleep Enable Disable'],['../group___r_c_c___a_p_b2___clock___sleep___enable___disable.html',1,'APB2 Peripheral Clock Sleep Enable Disable']]],
  ['sleep_20enabled_20or_20disabled_20status_69',['Sleep Enabled or Disabled Status',['../group___r_c_c___a_h_b1___clock___sleep___enable___disable___status.html',1,'AHB1 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_h_b2___clock___sleep___enable___disable___status.html',1,'AHB2 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_h_b3___clock___sleep___enable___disable___status.html',1,'AHB3 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_p_b1___clock___sleep___enable___disable___status.html',1,'APB1 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_p_b2___clock___sleep___enable___disable___status.html',1,'APB2 Peripheral Clock Sleep Enabled or Disabled Status']]],
  ['sleep_20mode_20entry_70',['PWR SLEEP mode entry',['../group___p_w_r___s_l_e_e_p__mode__entry.html',1,'']]],
  ['slot_20active_71',['SAI Block Slot Active',['../group___s_a_i___block___slot___active.html',1,'']]],
  ['slot_20size_72',['SAI Block Slot Size',['../group___s_a_i___block___slot___size.html',1,'']]],
  ['slot_20structure_20definition_73',['SAI Slot Structure definition',['../group___s_a_i___slot___structure__definition.html',1,'']]],
  ['smartcard_20aliased_20defines_20maintained_20for_20legacy_20purpose_74',['HAL SMARTCARD Aliased Defines maintained for legacy purpose',['../group___h_a_l___s_m_a_r_t_c_a_r_d___aliased___defines.html',1,'']]],
  ['smartcard_20aliased_20macros_20maintained_20for_20legacy_20purpose_75',['HAL SMARTCARD Aliased Macros maintained for legacy purpose',['../group___h_a_l___s_m_a_r_t_c_a_r_d___aliased___macros.html',1,'']]],
  ['smbus_20aliased_20defines_20maintained_20for_20legacy_20purpose_76',['HAL SMBUS Aliased Defines maintained for legacy purpose',['../group___h_a_l___s_m_b_u_s___aliased___defines.html',1,'']]],
  ['smbus_20aliased_20functions_20maintained_20for_20legacy_20purpose_77',['HAL SMBUS Aliased Functions maintained for legacy purpose',['../group___h_a_l___s_m_b_u_s___aliased___functions.html',1,'']]],
  ['smbus_20aliased_20macros_20maintained_20for_20legacy_20purpose_78',['HAL SMBUS Aliased Macros maintained for legacy purpose',['../group___h_a_l___s_m_b_u_s___aliased___macros.html',1,'']]],
  ['source_79',['Source',['../group___r_c_c_ex___a_d_c___clock___source.html',1,'ADC Clock Source'],['../group___r_c_c___a_h_b___clock___source.html',1,'AHB Clock Source'],['../group___r_c_c___a_p_b1___a_p_b2___clock___source.html',1,'APB1 APB2 Clock Source'],['../group___r_c_c_ex___i2_c1___clock___source.html',1,'I2C1 Clock Source'],['../group___r_c_c_ex___i2_c3___clock___source.html',1,'I2C3 Clock Source'],['../group___r_c_c_ex___l_s_c_o___clock___source.html',1,'Low Speed Clock Source'],['../group___r_c_c_ex___l_p_t_i_m1___clock___source.html',1,'LPTIM1 Clock Source'],['../group___r_c_c_ex___l_p_t_i_m2___clock___source.html',1,'LPTIM2 Clock Source'],['../group___r_c_c_ex___l_p_u_a_r_t1___clock___source.html',1,'LPUART1 Clock Source'],['../group___r_c_c___m_c_o1___clock___source.html',1,'MCO1 Clock Source'],['../group___r_c_c___p_l_l___clock___source.html',1,'PLL Clock Source'],['../group___r_c_c_ex___r_n_g___clock___source.html',1,'RNG Clock Source'],['../group___r_c_c___r_t_c___clock___source.html',1,'RTC Clock Source'],['../group___r_c_c___system___clock___source.html',1,'System Clock Source'],['../group___c_o_r_t_e_x___l_l___e_c___c_l_k_s_o_u_r_c_e___h_c_l_k.html',1,'SYSTICK Clock Source'],['../group___t_i_m___clear_input___source.html',1,'TIM Clear Input Source'],['../group___t_i_m___clock___source.html',1,'TIM Clock Source'],['../group___t_i_m___commutation___source.html',1,'TIM Commutation Source'],['../group___t_i_m___event___source.html',1,'TIM Event Source'],['../group___r_c_c_ex___u_s_a_r_t1___clock___source.html',1,'USART1 Clock Source'],['../group___r_c_c_ex___u_s_a_r_t2___clock___source.html',1,'USART2 Clock Source']]],
  ['source_80',['source',['../group___c_o_r_t_e_x___sys_tick__clock__source.html',1,'CORTEX SysTick clock source'],['../group___t_i_m_ex___break___input___source.html',1,'TIM Extended Break input source']]],
  ['source_20enabling_81',['TIM Extended Break input source enabling',['../group___t_i_m_ex___break___input___source___enable.html',1,'']]],
  ['source_20status_82',['System Clock Source Status',['../group___r_c_c___system___clock___source___status.html',1,'']]],
  ['sources_83',['TIM DMA Sources',['../group___t_i_m___d_m_a__sources.html',1,'']]],
  ['spdifrx_20aliased_20macros_20maintained_20for_20legacy_20purpose_84',['HAL SPDIFRX Aliased Macros maintained for legacy purpose',['../group___h_a_l___s_p_d_i_f_r_x___aliased___macros.html',1,'']]],
  ['speed_85',['GPIO speed',['../group___g_p_i_o__speed.html',1,'']]],
  ['speed_20clock_20source_86',['Low Speed Clock Source',['../group___r_c_c_ex___l_s_c_o___clock___source.html',1,'']]],
  ['spi_87',['SPI',['../group___s_p_i.html',1,'']]],
  ['spi_20aliased_20defines_20maintained_20for_20legacy_20purpose_88',['HAL SPI Aliased Defines maintained for legacy purpose',['../group___h_a_l___s_p_i___aliased___defines.html',1,'']]],
  ['spi_20aliased_20functions_20maintained_20for_20legacy_20purpose_89',['HAL SPI Aliased Functions maintained for legacy purpose',['../group___h_a_l___s_p_i___aliased___functions.html',1,'']]],
  ['spi_20aliased_20macros_20maintained_20for_20legacy_20purpose_90',['HAL SPI Aliased Macros maintained for legacy purpose',['../group___h_a_l___s_p_i___aliased___macros.html',1,'']]],
  ['spi_20baudrate_20prescaler_91',['SPI BaudRate Prescaler',['../group___s_p_i___baud_rate___prescaler.html',1,'']]],
  ['spi_20clock_20phase_92',['SPI Clock Phase',['../group___s_p_i___clock___phase.html',1,'']]],
  ['spi_20clock_20polarity_93',['SPI Clock Polarity',['../group___s_p_i___clock___polarity.html',1,'']]],
  ['spi_20crc_20calculation_94',['SPI CRC Calculation',['../group___s_p_i___c_r_c___calculation.html',1,'']]],
  ['spi_20crc_20length_95',['SPI CRC Length',['../group___s_p_i___c_r_c__length.html',1,'']]],
  ['spi_20data_20size_96',['SPI Data Size',['../group___s_p_i___data___size.html',1,'']]],
  ['spi_20direction_20mode_97',['SPI Direction Mode',['../group___s_p_i___direction.html',1,'']]],
  ['spi_20error_20code_98',['SPI Error Code',['../group___s_p_i___error___code.html',1,'']]],
  ['spi_20exported_20constants_99',['SPI Exported Constants',['../group___s_p_i___exported___constants.html',1,'']]],
  ['spi_20exported_20macros_100',['SPI Exported Macros',['../group___s_p_i___exported___macros.html',1,'']]],
  ['spi_20exported_20types_101',['SPI Exported Types',['../group___s_p_i___exported___types.html',1,'']]],
  ['spi_20fifo_20reception_20threshold_102',['SPI FIFO Reception Threshold',['../group___s_p_i___f_i_f_o__reception__threshold.html',1,'']]],
  ['spi_20flags_20definition_103',['SPI Flags Definition',['../group___s_p_i___flags__definition.html',1,'']]],
  ['spi_20interrupt_20definition_104',['SPI Interrupt Definition',['../group___s_p_i___interrupt__definition.html',1,'']]],
  ['spi_20mode_105',['SPI Mode',['../group___s_p_i___mode.html',1,'']]],
  ['spi_20msb_20lsb_20transmission_106',['SPI MSB LSB Transmission',['../group___s_p_i___m_s_b___l_s_b__transmission.html',1,'']]],
  ['spi_20nss_20pulse_20mode_107',['SPI NSS Pulse Mode',['../group___s_p_i___n_s_s_p___mode.html',1,'']]],
  ['spi_20private_20macros_108',['SPI Private Macros',['../group___s_p_i___private___macros.html',1,'']]],
  ['spi_20reception_20fifo_20status_20level_109',['SPI Reception FIFO Status Level',['../group___s_p_i__reception__fifo__status__level.html',1,'']]],
  ['spi_20slave_20select_20management_110',['SPI Slave Select Management',['../group___s_p_i___slave___select__management.html',1,'']]],
  ['spi_20ti_20mode_111',['SPI TI Mode',['../group___s_p_i___t_i__mode.html',1,'']]],
  ['spi_20transmission_20fifo_20status_20level_112',['SPI Transmission FIFO Status Level',['../group___s_p_i__transmission__fifo__status__level.html',1,'']]],
  ['spi_5fexported_5ffunctions_113',['SPI_Exported_Functions',['../group___s_p_i___exported___functions.html',1,'']]],
  ['spi_5fexported_5ffunctions_5fgroup1_114',['SPI_Exported_Functions_Group1',['../group___s_p_i___exported___functions___group1.html',1,'']]],
  ['spi_5fexported_5ffunctions_5fgroup2_115',['SPI_Exported_Functions_Group2',['../group___s_p_i___exported___functions___group2.html',1,'']]],
  ['spi_5fexported_5ffunctions_5fgroup3_116',['SPI_Exported_Functions_Group3',['../group___s_p_i___exported___functions___group3.html',1,'']]],
  ['spiex_117',['SPIEx',['../group___s_p_i_ex.html',1,'']]],
  ['spiex_5fexported_5ffunctions_118',['SPIEx_Exported_Functions',['../group___s_p_i_ex___exported___functions.html',1,'']]],
  ['spiex_5fexported_5ffunctions_5fgroup1_119',['SPIEx_Exported_Functions_Group1',['../group___s_p_i_ex___exported___functions___group1.html',1,'']]],
  ['sram2_20erase_20on_20reset_20type_120',['FLASH Option Bytes User SRAM2 Erase On Reset Type',['../group___f_l_a_s_h___o_b___u_s_e_r___s_r_a_m2___r_s_t.html',1,'']]],
  ['sram2_20page_20write_20protection_200_20to_2031_121',['SRAM2 Page Write protection (0 to 31)',['../group___s_y_s_c_f_g___s_r_a_m2_w_r_p.html',1,'']]],
  ['sram2_20parity_20check_20type_122',['FLASH Option Bytes User SRAM2 Parity Check Type',['../group___f_l_a_s_h___o_b___u_s_e_r___s_r_a_m2___p_e.html',1,'']]],
  ['sram2_20retention_20in_20standby_20mode_123',['PWR SRAM2 Retention in Standby mode',['../group___p_w_r_ex___s_r_a_m2___retention.html',1,'']]],
  ['standby_124',['Standby',['../group___f_l_a_s_h___o_b___u_s_e_r___i_w_d_g___s_t_a_n_d_b_y.html',1,'FLASH Option Bytes User IWDG Mode On Standby'],['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_t_a_n_d_b_y.html',1,'FLASH Option Bytes User Reset On Standby']]],
  ['standby_20mode_125',['PWR SRAM2 Retention in Standby mode',['../group___p_w_r_ex___s_r_a_m2___retention.html',1,'']]],
  ['standby_20shutdown_20mode_126',['GPIO bit number for I/O setting in standby/shutdown mode',['../group___p_w_r_ex___g_p_i_o___bit___number.html',1,'']]],
  ['start_20or_20stop_20mode_127',['I2C Start or Stop Mode',['../group___i2_c___s_t_a_r_t___s_t_o_p___m_o_d_e.html',1,'']]],
  ['state_128',['State',['../group___channel___c_c___state.html',1,'TIM Capture/Compare Channel State'],['../group___t_i_m___output___compare___n___idle___state.html',1,'TIM Complementary Output Compare Idle State'],['../group___t_i_m___output___compare___n___state.html',1,'TIM Complementary Output Compare State'],['../group___t_i_m___output___compare___idle___state.html',1,'TIM Output Compare Idle State'],['../group___t_i_m___output___compare___state.html',1,'TIM Output Compare State'],['../group___t_i_m___output___fast___state.html',1,'TIM Output Fast State'],['../group___u_a_r_t___state.html',1,'UART State']]],
  ['state_129',['state',['../group___t_i_m___o_s_s_i___off___state___selection__for___idle__mode__state.html',1,'TIM OSSI OffState Selection for Idle mode state'],['../group___t_i_m___o_s_s_r___off___state___selection__for___run__mode__state.html',1,'TIM OSSR OffState Selection for Run mode state']]],
  ['state_20and_20error_20functions_130',['Peripheral State and Error functions',['../group___u_a_r_t___exported___functions___group4.html',1,'']]],
  ['state_20code_20definition_131',['UART State Code Definition',['../group___u_a_r_t___state___definition.html',1,'']]],
  ['state_20functions_132',['State functions',['../group___t_i_m_ex___exported___functions___group7.html',1,'Extended Peripheral State functions'],['../group___t_i_m___exported___functions___group10.html',1,'TIM Peripheral State functions']]],
  ['state_20mode_20and_20error_20functions_133',['Peripheral State, Mode and Error functions',['../group___i2_c___exported___functions___group3.html',1,'']]],
  ['state_20structure_20definition_134',['HAL state structure definition',['../group___h_a_l__state__structure__definition.html',1,'']]],
  ['status_135',['Status',['../group___r_c_c___a_h_b1___peripheral___clock___enable___disable___status.html',1,'AHB1 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_h_b1___clock___sleep___enable___disable___status.html',1,'AHB1 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_h_b2___clock___enable___disable___status.html',1,'AHB2 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_h_b2___clock___sleep___enable___disable___status.html',1,'AHB2 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_h_b3___clock___enable___disable___status.html',1,'AHB3 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_h_b3___clock___sleep___enable___disable___status.html',1,'AHB3 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_p_b1___clock___enable___disable___status.html',1,'APB1 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_p_b1___clock___sleep___enable___disable___status.html',1,'APB1 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_p_b2___clock___enable___disable___status.html',1,'APB2 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_p_b2___clock___sleep___enable___disable___status.html',1,'APB2 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___system___clock___source___status.html',1,'System Clock Source Status']]],
  ['status_20and_20control_20registers_136',['Status and Control Registers',['../group___c_m_s_i_s___c_o_r_e.html',1,'']]],
  ['status_20flags_137',['Status Flags',['../group___p_w_r_ex___flag.html',1,'PWR Status Flags'],['../group___u_a_r_t___flags.html',1,'UART Status Flags']]],
  ['status_20level_138',['Status Level',['../group___s_a_i___block___fifo___status___level.html',1,'SAI Block Fifo Status Level'],['../group___s_p_i__reception__fifo__status__level.html',1,'SPI Reception FIFO Status Level'],['../group___s_p_i__transmission__fifo__status__level.html',1,'SPI Transmission FIFO Status Level']]],
  ['stereo_20mode_139',['SAI Mono Stereo Mode',['../group___s_a_i___mono___stereo___mode.html',1,'']]],
  ['stm32l476xx_140',['Stm32l476xx',['../group__stm32l476xx.html',1,'']]],
  ['stm32l4xx_141',['Stm32l4xx',['../group__stm32l4xx.html',1,'']]],
  ['stm32l4xx_5fhal_5fdriver_142',['STM32L4xx_HAL_Driver',['../group___s_t_m32_l4xx___h_a_l___driver.html',1,'']]],
  ['stm32l4xx_5fll_5fdriver_143',['STM32L4xx_LL_Driver',['../group___s_t_m32_l4xx___l_l___driver.html',1,'']]],
  ['stm32l4xx_5fsystem_144',['Stm32l4xx_system',['../group__stm32l4xx__system.html',1,'']]],
  ['stm32l4xx_5fsystem_5fexported_5fconstants_145',['STM32L4xx_System_Exported_Constants',['../group___s_t_m32_l4xx___system___exported___constants.html',1,'']]],
  ['stm32l4xx_5fsystem_5fexported_5ffunctions_146',['STM32L4xx_System_Exported_Functions',['../group___s_t_m32_l4xx___system___exported___functions.html',1,'']]],
  ['stm32l4xx_5fsystem_5fexported_5fmacros_147',['STM32L4xx_System_Exported_Macros',['../group___s_t_m32_l4xx___system___exported___macros.html',1,'']]],
  ['stm32l4xx_5fsystem_5fexported_5fvariables_148',['STM32L4xx_System_Exported_Variables',['../group___s_t_m32_l4xx___system___exported___variables.html',1,'']]],
  ['stm32l4xx_5fsystem_5fincludes_149',['STM32L4xx_System_Includes',['../group___s_t_m32_l4xx___system___includes.html',1,'']]],
  ['stm32l4xx_5fsystem_5fprivate_5fdefines_150',['STM32L4xx_System_Private_Defines',['../group___s_t_m32_l4xx___system___private___defines.html',1,'']]],
  ['stm32l4xx_5fsystem_5fprivate_5ffunctionprototypes_151',['STM32L4xx_System_Private_FunctionPrototypes',['../group___s_t_m32_l4xx___system___private___function_prototypes.html',1,'']]],
  ['stm32l4xx_5fsystem_5fprivate_5ffunctions_152',['STM32L4xx_System_Private_Functions',['../group___s_t_m32_l4xx___system___private___functions.html',1,'']]],
  ['stm32l4xx_5fsystem_5fprivate_5fincludes_153',['STM32L4xx_System_Private_Includes',['../group___s_t_m32_l4xx___system___private___includes.html',1,'']]],
  ['stm32l4xx_5fsystem_5fprivate_5fmacros_154',['STM32L4xx_System_Private_Macros',['../group___s_t_m32_l4xx___system___private___macros.html',1,'']]],
  ['stm32l4xx_5fsystem_5fprivate_5ftypesdefinitions_155',['STM32L4xx_System_Private_TypesDefinitions',['../group___s_t_m32_l4xx___system___private___types_definitions.html',1,'']]],
  ['stm32l4xx_5fsystem_5fprivate_5fvariables_156',['STM32L4xx_System_Private_Variables',['../group___s_t_m32_l4xx___system___private___variables.html',1,'']]],
  ['stop_157',['Stop',['../group___f_l_a_s_h___o_b___u_s_e_r___i_w_d_g___s_t_o_p.html',1,'FLASH Option Bytes User IWDG Mode On Stop'],['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_t_o_p.html',1,'FLASH Option Bytes User Reset On Stop']]],
  ['stop_20bits_158',['UART Number of Stop Bits',['../group___u_a_r_t___stop___bits.html',1,'']]],
  ['stop_20clock_159',['Wake-Up from STOP Clock',['../group___r_c_c___stop___wake_up_clock.html',1,'']]],
  ['stop_20mode_160',['I2C Start or Stop Mode',['../group___i2_c___s_t_a_r_t___s_t_o_p___m_o_d_e.html',1,'']]],
  ['stop_20mode_20enable_161',['UART Advanced Feature Stop Mode Enable',['../group___u_a_r_t___stop___mode___enable.html',1,'']]],
  ['stop_20mode_20entry_162',['PWR STOP mode entry',['../group___p_w_r___s_t_o_p__mode__entry.html',1,'']]],
  ['stop_20selection_163',['UART WakeUp From Stop Selection',['../group___u_a_r_t___wake_up__from___stop___selection.html',1,'']]],
  ['stretch_20mode_164',['I2C No-Stretch Mode',['../group___i2_c___n_o_s_t_r_e_t_c_h___m_o_d_e.html',1,'']]],
  ['strobing_165',['SAI Block Clock Strobing',['../group___s_a_i___block___clock___strobing.html',1,'']]],
  ['structure_20definition_166',['Structure definition',['../group___i2_c___configuration___structure__definition.html',1,'I2C Configuration Structure definition'],['../group___i2_c__handle___structure__definition.html',1,'I2C handle Structure definition'],['../group___s_a_i___frame___structure__definition.html',1,'SAI Frame Structure definition'],['../group___s_a_i___handle___structure__definition.html',1,'SAI Handle Structure definition'],['../group___s_a_i___init___structure__definition.html',1,'SAI Init Structure definition'],['../group___s_a_i___slot___structure__definition.html',1,'SAI Slot Structure definition']]],
  ['structure_20definition_167',['structure definition',['../group___h_a_l__mode__structure__definition.html',1,'HAL mode structure definition'],['../group___h_a_l__state__structure__definition.html',1,'HAL state structure definition']]],
  ['structures_168',['UTILS Exported structures',['../group___u_t_i_l_s___l_l___e_s___i_n_i_t.html',1,'']]],
  ['supported_20protocol_169',['SAI Supported protocol',['../group___s_a_i___protocol.html',1,'']]],
  ['swap_170',['UART Advanced Feature RX TX Pins Swap',['../group___u_a_r_t___rx___tx___swap.html',1,'']]],
  ['synchronisation_171',['SAI External synchronisation',['../group___s_a_i___block___sync_ext.html',1,'']]],
  ['synchronization_172',['SAI Block Synchronization',['../group___s_a_i___block___synchronization.html',1,'']]],
  ['syscfg_20aliased_20defines_20maintained_20for_20legacy_20purpose_173',['HAL SYSCFG Aliased Defines maintained for legacy purpose',['../group___h_a_l___s_y_s_c_f_g___aliased___defines.html',1,'']]],
  ['syscfg_20exported_20constants_174',['SYSCFG Exported Constants',['../group___s_y_s_c_f_g___exported___constants.html',1,'']]],
  ['syscfg_20exported_20macros_175',['SYSCFG Exported Macros',['../group___s_y_s_c_f_g___exported___macros.html',1,'']]],
  ['syscfg_20private_20macros_176',['SYSCFG Private Macros',['../group___s_y_s_c_f_g___private___macros.html',1,'']]],
  ['system_177',['SYSTEM',['../group___u_t_i_l_s___e_f___s_y_s_t_e_m.html',1,'']]],
  ['system_178',['TIM Break System',['../group___t_i_m___break___system.html',1,'']]],
  ['system_20clock_20source_179',['System Clock Source',['../group___r_c_c___system___clock___source.html',1,'']]],
  ['system_20clock_20source_20status_180',['System Clock Source Status',['../group___r_c_c___system___clock___source___status.html',1,'']]],
  ['system_20clock_20type_181',['System Clock Type',['../group___r_c_c___system___clock___type.html',1,'']]],
  ['system_20control_20block_20scb_182',['System Control Block (SCB)',['../group___c_m_s_i_s___s_c_b.html',1,'']]],
  ['system_20controls_20not_20in_20scb_20scnscb_183',['System Controls not in SCB (SCnSCB)',['../group___c_m_s_i_s___s_cn_s_c_b.html',1,'']]],
  ['system_20tick_20timer_20systick_184',['System Tick Timer (SysTick)',['../group___c_m_s_i_s___sys_tick.html',1,'']]],
  ['systick_185',['SYSTICK',['../group___c_o_r_t_e_x___l_l___e_f___s_y_s_t_i_c_k.html',1,'']]],
  ['systick_186',['System Tick Timer (SysTick)',['../group___c_m_s_i_s___sys_tick.html',1,'']]],
  ['systick_20clock_20source_187',['SYSTICK Clock Source',['../group___c_o_r_t_e_x___l_l___e_c___c_l_k_s_o_u_r_c_e___h_c_l_k.html',1,'']]],
  ['systick_20clock_20source_188',['CORTEX SysTick clock source',['../group___c_o_r_t_e_x___sys_tick__clock__source.html',1,'']]],
  ['systick_20functions_189',['SysTick Functions',['../group___c_m_s_i_s___core___sys_tick_functions.html',1,'']]]
];
